testproject/accounts/urls.py
from django.urls import path,include

from . import views

app_name = 'accounts'


urlpatterns = [

    path('signup/', views.signup, name='signup'),
    path('profile/', views.profile, name='profile'),
    path('profile/edit/', views.profile_edit, name='profile_edit'),

    ]

testproject/fin/urls.py
from django.urls import path

from . import views


urlpatterns = [



    path('fin/update/<pk>/', views.finbookUpdateView.as_view(), name='finupdate'),
    path('fin/new/', views.CreatefinbookView.as_view(), name='finnew'),
    path('fin/description/new', views.newdis, name='newdis'),
    path('fin/index', views.index, name='index'),
    path('fin/<pk>/', views.finbookDetailView.as_view(), name='transactiondetail'),
    path('fin/newdis/', views.newdis, name='newdis'),
    path('mytext/', views.mystream, name='mystream'),
    path('anova10/', views.anova, name='anova10'),
    path('twit/', views.fillsource, name='fillsource'),
    path('testtext/', views.testtext, name='testtext'),
    path('myimport/', views.myimport, name='myimport'),

    path('project/new/', views.projectnew, name='projectnew'),
    path('project/<pk>/', views.projectDetailView.as_view(), name='projectdetail'),
    path('project/<pk>/delete', views.projectDeleteView.as_view(), name='projectdelete'),
    path('project/', views.projectlist, name='projectlist'),
    path('project/update/<pk>/', views.projectUpdateView.as_view(), name='projectupdate'),

    path('search/new/<pk>/', views.searchnew, name='searchnew'),
    path('search/<pk>/', views.searchdetail, name='searchdetail'),
    path('search/<pk>/delete', views.searchDeleteView.as_view(), name='searchdelete'),
    path('search/', views.searchlist, name='searchlist'),
    path('search/update/<pk>/', views.searchUpdateView.as_view(), name='searchupdate'),
    path('searchrun/<pk>/', views.searchrun, name='searchrun'),
    path('searchrun2/<pk>/', views.searchrun2, name='searchrun2'),
    path('searchrun3', views.searchrun3, name='searchrun3'),

        ]

testproject/testproject/urls.py
from django.contrib import admin
from django.urls import path,include
from fin import views



urlpatterns = [

    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('admin/', admin.site.urls),
    path('fin/', include('fin.urls')),
    path('', views.home,name='home'),

]

testproject/fin/forms.py
from django import forms

from .models import finbook,textstream,category,project,search,searchdetails


class finbookForm(forms.ModelForm):
    class Meta:
        model = finbook
        fields = ('description','clarification','category')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['city'].queryset = City.objects.none()

class desForm(forms.ModelForm):

    class Meta:
        model = finbook
        fields = ('description',)

        widgets = {
            'title': forms.TextInput(attrs={'class': 'textinputclass'}),
            'text': forms.Textarea(attrs={'class': 'editable medium-editor-textarea postcontent'}),
        }

class textstreamForm(forms.ModelForm):

    class Meta:
        model = textstream
        fields = ('mytext','impression',)

        widgets = {
            'title': forms.TextInput(attrs={'class': 'textinputclass'}),
            'text': forms.Textarea(attrs={'class': 'editable medium-editor-textarea postcontent'}),
        }

class projectForm(forms.ModelForm):

    class Meta:
        model = project
        fields = ('projectname','note',)

        widgets = {
            'title': forms.TextInput(attrs={'class': 'textinputclass'}),
            'text': forms.Textarea(attrs={'class': 'editable medium-editor-textarea postcontent'}),
        }

class searchForm(forms.ModelForm):

    class Meta:
        model = search
        fields = ('searchname','note',)

        widgets = {
            'title': forms.TextInput(attrs={'class': 'textinputclass'}),
            'text': forms.Textarea(attrs={'class': 'editable medium-editor-textarea postcontent'}),
        }

class searchrunForm(forms.Form):


    word1 = forms.CharField(max_length=100, label='First Kye Word')
    word2 = forms.CharField(max_length=100, label='Second Kye Word')
    maxi = forms.IntegerField()

    

testproject/fin/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.db.models import F
from django.utils import timezone
from django.http import HttpResponseRedirect
import datetime
from datetime import timedelta
from django.shortcuts import redirect
from django.urls import reverse
from django.contrib.auth.models import User
from .models import finbook,textstream,sentmentlist,project,search,searchdetails
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import permission_required
from django.db.models import Count , Sum , Avg
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from eventregistry import *
import json
from django.urls import reverse_lazy
from .filters import textstreamFilter
from .forms import finbookForm,projectForm,searchForm,searchrunForm
from django.shortcuts import get_object_or_404, render
from django.views.generic import (TemplateView,ListView,
                                  DetailView,CreateView,
                                  UpdateView,DeleteView)



YOUTUBE_API_KEY ='AIzaSyAWSRZJ-Dhm0nVKK7GYp8siNSnWwnJUwYM'
def index(request):

    mysearch = textstream.objects.all().order_by('-id')
    myfilter = mysearchFilter(request.GET,queryset=mysearch)
    mysearch = myfilter.qs

    paginator = Paginator(mysearch,20)
    page = request.GET.get('page')
    try:
        opps = paginator.page(page)
    except PageNotAnInteger:
        opps = paginator.page(1)
    except EmptyPage:
        opps = paginator.page(paginator.num_pages)


    context = {'mysearch':mysearch,'opps':opps}
    return render(request, 'fin/textstream.html',context)
    # finlist = finbook.objects.all().order_by('-creationdate')
    # context = {'finlist':finlist}
    # return render(request, 'fin/index.html',context)

class finbookUpdateView(UpdateView):
    redirect_field_name = 'fin/finbook_detail.html'
    form_class = finbookForm
    model = finbook

class CreatefinbookView(CreateView):
    redirect_field_name = 'fin/finbook_detail.html'
    form_class = finbookForm
    model = finbook

class finbookDetailView(DetailView):
    model = finbook

def newdis(request):
    pass

def mystream(request):

    mysearch = textstream.objects.all().order_by('-id')
    myfilter = mysearchFilter(request.GET,queryset=mysearch)
    mysearch = myfilter.qs

    paginator = Paginator(mysearch,20)
    page = request.GET.get('page')
    try:
        opps = paginator.page(page)
    except PageNotAnInteger:
        opps = paginator.page(1)
    except EmptyPage:
        opps = paginator.page(paginator.num_pages)


    context = {'mysearch':mysearch,'opps':opps}
    return render(request, 'fin/textstream.html',context)

def anova(request):
    mysearch = textstream.objects.all()
    alltext = textstream.objects.all()

    pos = sentmentlist.objects.filter(imporession='Positive').values_list('myword')
    posall = sentmentlist.objects.filter(imporession='Positive')
    poslist=posall.values_list('imporession', flat=True)


    negall = sentmentlist.objects.filter(imporession='Negative')
    neglist=negall.values_list('imporession', flat=True)


    text1 = textstream.objects.filter(impression='Neutral').exclude(frequency=5)[0:1000]
    for text in text1:
        text.frequency = 5
        texts = text.mytext.split()
        for word in texts:
            if word.lower() in poslist:
                text.impression = 'Positive'

            elif word.lower() in neglist:
                text.impression = 'Negative'

        text.save()

    fre5 = textstream.objects.filter(impression='Neutral').exclude(frequency=5)
    myfilter = textstreamFilter(request.GET,queryset=mysearch)
    mysearch = myfilter.qs

    paginator = Paginator(mysearch,20)
    page = request.GET.get('page')
    try:
        opps = paginator.page(page)
    except PageNotAnInteger:
        opps = paginator.page(1)
    except EmptyPage:
        opps = paginator.page(paginator.num_pages)

    languager =  mysearch.values('lang').annotate(Total=Count('id')).order_by('-Total')[0:20]
    languageall = alltext.values('lang').annotate(Total=Count('id')).order_by('-Total')[0:20]
    locationr = mysearch.values('location').annotate(Total=Count('id')).order_by('-Total')[0:20]
    locationall = alltext.values('location').annotate(Total=Count('id')).order_by('-Total')[0:20]
    impr = mysearch.values('impression').annotate(Total=Count('id'))
    impall = alltext.values('impression').annotate(Total=Count('id'))
    emotionnull = textstream.objects.filter(emotion='No thing').exclude(impression='No thing')[0:50]
    for em in emotionnull:
        em.emotion = em.impression
        em.save()
    emall = alltext.values('emotion').annotate(Total=Count('id'))
    emotionnull = textstream.objects.filter(emotion='No thing').exclude(impression='No thing')

    context = {'fre5':fre5,'poslist':poslist,'posall':posall,'negall':negall,'pos':pos,'emotionnull':emotionnull,'emall':emall,'impr':impr,'impall':impall,'locationr':locationr,'locationall':locationall,'languageall':languageall,'mysearch':mysearch,'opps':opps,'myfilter':myfilter,'languager':languager}
    return render(request, 'fin/textstream.html',context)

def fillsource(request):
    pl = []
    nl = []
    alltext  = textstream.objects.filter(mytext__contains='kill').filter(impression = 'No thing')
    mypositive = sentmentlist.objects.filter(imporession='Positive').values('myword').distinct()
    mynegative = sentmentlist.objects.filter(imporession='Negative').values('myword').distinct()
    for zz in mypositive:
        pl.append(zz["myword"])
    for nn in mynegative:
        nl.append(nn["myword"])
    for dd in alltext:
        if dd.impression=='No thing':

            dds = dd.mytext.split()
            for dds1 in dds:
                dds1 = dds1.lower()
                if dds1 in pl :
                    dd.impression = 'Positive'
                    dd.save()
                    break
                elif dds1 in nl :
                    dd.impression = 'Negative'
                    dd.save()
                    break



    context = {'alltext':alltext,'mypositive':mypositive,'mynegative':mynegative,'pl':pl,'nl':nl}
    return render(request, 'fin/twit.html',context)

def testtext(request):
    posall = sentmentlist.objects.filter(imporession='Positive')
    poslist=posall.values_list('imporession', flat=True)

    negall = sentmentlist.objects.filter(imporession='Negative')
    neglist=negall.values_list('imporession', flat=True)

    nosent=[]
    nutraltext  = textstream.objects.filter(impression = 'Neutral')
    for text in nutraltext:
        texts = text.mytext.split()
        for word in set(texts):
            word = word.lower()
            if len(word) > 3:
                if word.isalpha():

                    if word not in poslist:
                        if word not in neglist:
                            if word not in nosent:
                                nosent.append(word)
    nosent.sort()
    nosentl = len(nosent)

    context = {'nutraltext':nutraltext,'nosent':nosent,'poslist':poslist,'nosentl':nosentl}
    return render(request, 'fin/testtext.html',context)

def home(request):

    myprojects = project.objects.filter(creator=request.user)
    context = {'myprojects':myprojects}
    return render(request,'fin/home.html',context)

def myimport(request):
    aa = 'Saudi Arabia'
    er = EventRegistry(apiKey = 'f97425bc-cc68-4da2-a302-9be8eb8ad153')
    bb = ''
    q = QueryArticlesIter(
        keywords = QueryItems.OR([aa, bb]),
        dataType = ["news", "blog"])
    # obtain at most 500 newest articles or blog posts
    q1 = q.execQuery(er, sortBy = "date", maxItems = 10)
    context = {'q1':q1}
    return render(request, 'fin/myimport.html',context)

# project=========================

def projectnew(request):
    if request.method=='POST':
        form = projectForm(request.POST)
        if form.is_valid():
            myform = form.save(commit=False)
            myform.creator=request.user

            myform.save()
            pk = myform.id
            return HttpResponseRedirect(reverse('projectdetail', args=(pk,)))

    else:
        form = projectForm()
    return render(request, 'fin/project_form.html',{'form':form})

class projectDetailView(DetailView):
    model = project

class projectDeleteView(DeleteView):
    model = project
    success_url = reverse_lazy('projectlist')

@login_required
def projectlist(request):
    projectlist = project.objects.filter(creator=request.user).order_by('-creationdate')
    context = {'projectlist':projectlist}
    return render(request, 'fin/projectlist.html',context)

class projectUpdateView(UpdateView):
    redirect_field_name = 'fin/project_detail.html'
    form_class = projectForm
    model = project


# Search============================


def searchnew(request,pk):
    if request.method=='POST':
        form = searchForm(request.POST)
        myproject = get_object_or_404(project,pk=pk)
        if form.is_valid():
            myform = form.save(commit=False)
            myform.creator=request.user
            myform.project = myproject

            myform.save()
            pk = myform.id
            return HttpResponseRedirect(reverse('searchdetail', args=(pk,)))

    else:
        form = searchForm()
    return render(request, 'fin/search_form.html',{'form':form})

def searchdetail(request,pk):
    searchnow = get_object_or_404(search,pk=pk)
    searchtexts = searchnow.search_texts.all()
    languager =  searchtexts.values('lang').annotate(Total=Count('id')).order_by('-Total')
    impr = searchtexts.values('impression').annotate(Total=Count('id')).order_by('-Total')
    context = {'searchnow':searchnow,'searchtexts':searchtexts,'languager':languager,'impr':impr}
    return render(request, 'fin/search_detail.html',context)

class searchDeleteView(DeleteView):
    model = search
    success_url = reverse_lazy('searchlist')

@login_required
def searchlist(request):

testproject/fin/templates/fin/base.html
<!DOCTYPE html>
{% load crispy_forms_tags %}
<html lang="en" dir="ltr">
  <head>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

  {% block title %} {%endblock%}



</head>
  <body>


  <div class="container mt-2">




    <nav class="navbar navbar-expand-lg navbar-light bg-primary ">
  <a class="navbar-item text-light h5" href="{% url 'home' %} " >Home</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link text-light h5" href="{% url 'projectlist' %}">Projects <span class="sr-only">(current)</span></a>
      </li>

      <li class="nav-item active">
        <a class="nav-link text-light h5" href="">About Us</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link text-light h5" href="">Pricing<span class="sr-only">(current)</span></a>
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle text-primary h5" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Sales
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'home' %}">Opportunities</a>
          <a class="dropdown-item" href="{% url 'home' %}">Post Opportunities</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#"></a>
        </div>
      </li>

<!-- operation start -->
<li class="nav-item dropdown">
  <a class="nav-link dropdown-toggle text-primary h5" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    aaa
  </a>
  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
    <a class="dropdown-item" href="{% url 'home' %}">aaa</a>
    <a class="dropdown-item" href="{% url 'home' %}">aaa</a>


    <div class="dropdown-divider"></div>
    <a class="dropdown-item" href="{% url 'home' %}">aa</a>
    <a class="dropdown-item" href="{% url 'home' %}">aa</a>
  </div>
</li>



{% if user.username %}
<button  class="btn btn-outline-primary " style="font-weight: bold;text-align:right;">{{user.username}}</a></button>
<a class="nav-link text-primary h5 " style="font-weight: bold;text-align:right;" href="{% url 'logout' %}">Logout<span class="sr-only">(current)</span></a>
{% else %}
<a class="nav-link text-primary h5 p-2" href="{% url 'login' %}">Login<span class="sr-only">(current)</span></a>
<a class="nav-link text-primary h5 p-2" href="{% url 'accounts:signup' %}">Signup<span class="sr-only">(current)</span></a>
{% endif %}
{% if user.username %}
<button  class="btn btn-outline-primary " style="font-weight: bold;text-align:right;">{{user.username}}</a></button>
<a class="nav-link text-primary h5 " style="font-weight: bold;text-align:right;" href="{% url 'logout' %}">Logout<span class="sr-only">(current)</span></a>
{% else %}
<a class="nav-link text-primary h5 p-2" href="{% url 'login' %}">Login<span class="sr-only">(current)</span></a>
<a class="nav-link text-primary h5 p-2" href="{% url 'accounts:signup' %}">Signup<span class="sr-only">(current)</span></a>
{% endif %}



{% if user.username %}
<button  class="btn btn-outline-warning " style="font-weight: bold;text-align:right;">{{user.username}}</a></button>
<a class="nav-link text-dark h5 " style="font-weight: bold;text-align:right;" href="{% url 'logout' %}">Logout<span class="sr-only">(current)</span></a>
{% else %}
<a class="nav-link text-success h5 p-2" href="{% url 'login' %}">Login<span class="sr-only">(current)</span></a>
<a class="nav-link text-success h5 p-2" href="{% url 'accounts:signup' %}">Signup<span class="sr-only">(current)</span></a>
{% endif %}



</nav>




</div>

{% block content %}
  {% endblock %}


</script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>


{% block javascript %}

{% endblock %}


  </body>
</div>

</html>

testproject/fin/templates/fin/finbook_detail.html
{% extends 'fin/base.html' %}
{% load crispy_forms_tags %}


{% block title %}<title>Transaction</title> {%endblock%}

{% block content %}




  <br>
  <div class="container">

<div class="row">
<div class="column ">




</div>



<div class="column">



</div>
<table class="table mt-4">
    <thead class="thead-dark">
  <tr>

    <th class="text-center">Discreption</th>
    <th class="text-center">Clarification</th>
    <th class="text-center">Transaction</th>
    <th class="text-center">Amount</th>
    <th class="text-center">Transaction Date</th>
    <th class="text-center">Category</th>
    <th class="text-center">Department</th>
    <th class="text-center">Sub Department</th>
    <th class="text-center">Source</th>
    <th class="text-center">Note</th>
  </tr>


  <tr>
  <td class="border text-center">{{finbook.description}}</td>
  <td class="border text-center">{{finbook.clarification}}</td>
  <td class="border text-center">{{finbook.transactionc}}</td>
  <td class="border text-center">{{finbook.amount}}</td>
  <td class="border text-center">{{finbook.transactiondate}}</td>
  <td class="border text-center">{{finbook.category}}</td>
  <td class="border text-center">{{finbook.department}}</td>
  <td class="border text-center">{{finbook.subdepartment}}</td>
  <td class="border text-center">{{finbook.incomesource}}</td>
  <td class="border text-center">{{finbook.note}}</td>
  </tr>

</table>

<br>

<div class="column"></div>


</div>
</div>

{% endblock %}

testproject/fin/templates/fin/finbook_form.html
{% extends 'hadeeth/base.html' %}

{% load crispy_forms_tags %}

{% block content %}

<div class="container">

  <br>

<h6>Add Fatwa</h6>


<h2>Fin Form</h2>
  <form method="post" novalidate>
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <button type="submit">Save</button>
    <a href="{% url 'index' %}">Nevermind</a>
  </form>

</div>

{% endblock %}

testproject/fin/templates/fin/home.html
{% extends 'fin/base.html' %}


{% block content %}

<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Berkshire+Swash&display=swap" rel="stylesheet">

<div class="container">


    <h2 class="display-2 m-5" style="color:black;font-family: 'Berkshire Swash', cursive;"><b>Anova PlatForm </b></h2>





  <div class="jumbotron mt-3">
    <h2 class="display-5" style="color:tomato;font-family:verdana;"><b>Welcome To Anova PlatForm For Media Monitoring</b></h2>
    <p class="lead">Monitor media coverage across online, print, broadcast, and social media with an easy-to-use tool..</p>
    <hr class="my-4">
    <p  ></p>
    <p class="lead">
      {% if myprojects %}
      <a class="btn btn-primary btn-lg" href="{% url 'projectlist' %}" role="button">Go To My Projects</a>
      {% else %}

      <a class="btn btn-primary btn-lg" href="#" role="button">Create Your First Project</a>
      {% endif %}
    </p>
  </div>



</div>





{% endblock %}

testproject/fin/templates/fin/myimport.html
{% extends 'fin/base.html' %}


{% block content %}
<br>



{% for art in q1 %}

<p>{{art}}</p>
<br>
<p>{{art.sentiment}}</p>

<hr>
{% endfor %}


<p>=======================</p>

{{q1}}


{% endblock %}

testproject/fin/templates/fin/mysearch_form.html
{% extends 'fin/base.html' %}

{% load crispy_forms_tags %}

{% block content %}

<div class="container">

  <br>

<h6>Start a  Search</h6>




    <form method="POST" class="post-form">

    {% csrf_token %}
    <form  method="post">
    <label for="team_name">Enter name: </label>
    <input id="team_name" type="text" name="name_field" value="Default name for team.">
    <input type="submit" value="OK">
    </form>

    <button type="submit" class="btn btn-primary mb-2">Save</button>

    </form>

</div>

{% endblock %}

testproject/fin/templates/fin/project_confirm_delete.html
{% extends 'fin/base.html' %}

{% block content %}

<div class="container mt-5">


<form method="post">{% csrf_token %}
    <p class="text-danger">Are you sure you want to delete </p>
    <br>
    <br>
<h1>  {{ object }}</h1>


    <input type="submit" value="Confirm" class="mt-5 btn btn-danger">
</form>

</div>



{% endblock %}

testproject/fin/templates/fin/project_detail.html
{% extends 'fin/base.html' %}
{% load crispy_forms_tags %}


{% block title %}<title></title> {%endblock%}

{% block content %}


  <br>
  <div class="container">




<table class="table mt-4">
    <thead class="thead-dark">
  <tr>

    <th class="text-center">Project Name</th>
    <th class="text-center">Creation Date</th>
    <th class="text-center">Note</th>


  </tr>

  <tr>

  <td class="border text-center">{{project.projectname}}</td>
  <td class="border text-center">{{project.creationdate}}</td>
  <td class="border text-center">{{project.note}}</td>



  </tr>

</table>

<button type="button" class="btn btn-success btn-sm">

  <a href="{% url 'searchnew' pk=project.pk %}" class="text-light">Add New Search </a>
  <span class="sr-only">unread messages</span>
</button>


<br>

<button type="button" class="btn btn-danger btn-sm">

  <a href="{% url 'projectdelete' pk=project.pk %}" class="text-light">Delete </a>
  <span class="sr-only">unread messages</span>
</button>

<button type="button" class="btn btn-link"><a href="{% url 'projectupdate' pk=project.id %}">Update</a></button>

<hr>

{% if project.project_searches.all %}

<div class="p-1 mb-2 mt-5 bg-warning text-dark d-flex justify-content-center"><h5 >List Of Searches</h5></div>
<table class="table mt-1">
    <thead class="thead-light">
  <tr>

    <th class="text-center">Project Name</th>
    <th class="text-center">Creation Date</th>
    <th class="text-center">Note</th>
    <th class="text-center">No Of Texts</th>
  </tr>
{% for search in project.project_searches.all %}
  <tr>

    <td class="border text-center"><a href="{% url 'searchdetail' pk=search.id %}">{{search.searchname}}</a></td>
    <td class="border text-center">{{search.creationdate}}</td>
    <td class="border text-center">{{search.note}}</td>
    <td class="border text-center">{{search.search_texts.count}}</td>

  </tr>
{% endfor %}
</table>
{% else%}

<h5>There is no Searches</h5>

{% endif %}


</div>


{% endblock %}

testproject/fin/templates/fin/projectlist.html
{% extends 'fin/base.html' %}


{% block content %}



<div class="container mt-5">

  <h4 class="text-center m-1 text-success">No of My projects : {{projectlist.count}}</h4>

  {% if projectlist %}

  <table class="table mt-5">
      <thead class="thead-dark">
    <tr>
      <th class="text-center">Project Name</th>
      <th class="text-center">Creation Date</th>
      <th class="text-center">Note</th>


    </tr>
    {% for project in projectlist %}
    <tr>
      <td class="border text-center"><a href="{% url 'projectdetail' pk=project.id %}">{{project.projectname}}</a></td>
      <td class="border text-center">{{project.creationdate}}</td>
      <td class="border text-center">{{project.note}}</td>

    </tr>
    {% endfor %}
  </table>
  {% endif %}

<a class="btn btn-info btn-lg" href="{% url 'projectnew' %}" role="button">Create New Project</a>



</div>
{% endblock %}

testproject/fin/templates/fin/result.html
{{result1}}
<br>
{% for kk in result1 %}

{% for ll in kk.items %}

<span>{{ll.0}} <span>:</span> {{ll.1}}</span>
<hr>
{% endfor %}

{% endfor %}

<hr>

{% for kk in result1 %}


{{kk.lang}}
<br>
{% endfor %}


<hr>

testproject/fin/templates/fin/search_form.html
{% extends 'fin/base.html' %}

{% load crispy_forms_tags %}

{% block content %}

<div class="container">

  <br>

<h6>Add Search</h6>




    <form method="POST" class="post-form">

    {% csrf_token %}
    {{form|crispy}}

    <button type="submit" class="btn btn-primary mb-2">Save</button>

    </form>

</div>

{% endblock %}

testproject/fin/templates/fin/searchlist.html
{% extends 'fin/base.html' %}


{% block content %}



<div class="container mt-5">

  <h4 class="text-center m-1 text-success">No of My searchs : {{searchlist.count}}</h4>

  {% if searchlist %}

  <table class="table mt-5">
      <thead class="thead-dark">
    <tr>
      <th class="text-center">Project Name</th>
      <th class="text-center">Search Name</th>
      <th class="text-center">Creation Date</th>
      <th class="text-center">Note</th>

    </tr>
    {% for search in searchlist %}
    <tr>
      <td class="border text-center"><a href="{% url 'searchdetail' pk=search.id %}">{{search.searchname}}</a></td>
      <td class="border text-center">{{search.project}}</td>
      <td class="border text-center">{{search.searchname}}</td>
      <td class="border text-center">{{search.creationdate}}</td>
      <td class="border text-center">{{search.note}}</td>


    </tr>
    {% endfor %}
  </table>
  {% endif %}





</div>
{% endblock %}

testproject/fin/templates/fin/twit.html
<h1>twit : {{twit}}</h1>

<h1>ALL : {{allsum}}</h1>



<h2>Source Reports</h2>

<p>{{xx.source}}:{{xx.Total}}</p>
<br>

<hr>
<h1>{{alltext.count}}</h1>
<h1>{{mypositive.count}}</h1>
<h1>{{mynegative.count}}</h1>
<h1>{{pl}}</h1>

<h1>{{nl}}</h1>

<button type="button" name="button"><a href="https://newsapi.org/v2/everything?q=bitcoin&apiKey=605ea7926f454335b92310fa1034b243">News Paper</a></button>

<p>{{alltext}}</p>